remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

title: theadamwright.github.io
description: Databases, Security, and K8s 

#theme: minima

# description (displayed in the header)
# description: databases, software security, and K8s
